### ISSUE TITLE
Fails with "No node found for selector" after login

### ISSUE THREAD

**Issue by Ben-Voris** [1fge/my-pandora-likes#2]
python3 --version prints Python 3.6.9

I had to run "pip3" instead of "pip". It completed without any obvious errors.

I can login to Pandora using the value of email and password from `pandora_likes.py`.

```
: python3 pandora_likes.py
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
100%|███████████████████████████████████████████████████████████████████████████| 108773488/108773488 [00:01<00:00, 60462648.38it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /home/bvoris/.local/share/pyppeteer/local-chromium/588429
Browser Login Attempt (1)
Traceback (most recent call last):
  File "pandora_likes.py", line 170, in <module>
    downloader.download_likes()
  File "pandora_likes.py", line 157, in download_likes
    cookies, login_response_json = loop.run_until_complete(self.stealth_login.fetch_login_data())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/bvoris/my-pandora-likes/stealth_login.py", line 64, in fetch_login_data
    await self.page.hover("#form-template > div:nth-child(3) > div > button")
  File "/home/bvoris/.local/lib/python3.6/site-packages/pyppeteer/page.py", line 1556, in hover
    await frame.hover(selector)
  File "/home/bvoris/.local/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 605, in hover
    raise PageError('No node found for selector: ' + selector)
pyppeteer.errors.PageError: No node found for selector: #form-template > div:nth-child(3) > div > button
```

**Comment by 1fge** [comment]
Thanks for reporting this bug, I'll look into it sometime this week 😃

**Comment by 1fge** [comment]
The most recent commit fixes the login issue & also uses the mobile app API to fetch song information now. Feel free to open a new issue if you run into other problems.
